### ISSUE TITLE
FriendsManager not populating table

### ISSUE THREAD

**Issue by wkentdag** [sbwf/sup-client#4]
It pulls the relevant information from the server but fails to populate it to the table.

Also, need to figure out how to concatenate strings and integers into the full URL - using static `http://localhost:3000/users/2/friends` as placeholder for now

**Comment by wkentdag** [comment]
@Shurlow I think there's a problem with `makeRequest` string concatenation. GETting `localhost:3000/requests/2` or some other ID works fine, but `localhost:3000/users/2/friends` or some other ID fails. I rewrote the "get friends of user" route with this style: `/friends/u/:id`, and that call was able to pull data once before failing every time thereafter (???).

**Comment by wkentdag** [comment]
now it works tho?
![ios simulator screen shot may 4 2015 9 26 40 pm](https://cloud.githubusercontent.com/assets/3254957/7466200/5b19da1a-f2a4-11e4-8d68-265f9e049a25.png)

**Comment by sbwf** [comment]
so rewriting the route worked but only one time?

**Comment by wkentdag** [comment]
Yeah. i think there is something wrong either with the makeRequest function or with the way we're storing myId after it gets initially set, or both

**Comment by wkentdag** [comment]
fixed [here](https://github.com/wkentdag/sup/commit/7248bededf3bf25a84e16ad87fbc2fa5052f6655)
